name: BEF Release Test Candidate

on:
  # manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v2

      - name: Get Time for BUILD_ID
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD_HHmm'

      - name: Get Branch name for BUILD_LABEL
        id: branch_name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Everything
        env:
          BUILD_ID: "${{ steps.time.outputs.time }}"
          BUILD_TYPE: "S"
          BUILD_LABEL: "CI ${{ steps.time.outputs.time }} (${{ steps.branch_name.outputs.branch }})"
        run: mvn --batch-mode clean verify "-Dtest=\!com.salesforce.b2eclipse.*"

      - name: Create the update-site-release-candidate layout on the filesystem
        id: create_layout
        shell: bash
        run: .github/bef-create-update-site-rc.sh

      - name: Deploy Update Site ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: bef-rc-staging
          clean: false
          commit-message: bef-release-candidate
          ssh-key: ${{ secrets.DEPLOY_KEY }}
